#!C:\Users\magdalena.kurlanc\OneDrive - Lingaro Sp. z o. o\DSS\TRANS\live_translator-dev\env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
